(cl:defpackage ouster_lidar-msg
  (:use )
  (:export
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTARRAY>"
   "DETECTEDOBJECTARRAY"
   "<MARKERCLASSIFICATION>"
   "MARKERCLASSIFICATION"
   "<MARKERWITHCLOUD>"
   "MARKERWITHCLOUD"
   "<MARKERWITHCLOUDARRAY>"
   "MARKERWITHCLOUDARRAY"
  ))

